openapi: 3.0.0
info:
  title: My API
  description: A simple API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
